### ISSUE TITLE
How do we replicate train/test split in paper?

### ISSUE THREAD

**Issue by wcarvalho** [deepmind/pushworld#1]
Thanks for sharing this! It's a really exciting environment.

It's not clear how to replicate the results in Table 2. Specifically, it's not clear which of the [level 1](https://github.com/deepmind/pushworld/tree/main/benchmark/puzzles/level1) are train, and which are test (you say level 0 in paper btw). 

Also, it's not obvious how to get the settings: "Larger Puzzle Sizes", "More Walls", "More Obstacles", "More Shapes", "Multiple Goals". 

Really appreciate any help here! Thanks

**Comment by kkansky** [comment]
Nice to meet you, Wilka! 

Section 5.3 in the paper describes the procedure to replicate Table 2, including the definition of the Level 0 puzzle sets. We did not train on any Level 1 puzzles during the Level 0 experiments. Next week we will release the code to generate the Level 0 sets, including train/test splits, and I hope it will be useful for your experiments.

**Comment by xloudm** [comment]
Hey @wcarvalho,

Thanks for our interest. We have added the Level0 dataset to this repo. See level0.zip under https://github.com/deepmind/pushworld/tree/main/benchmark/puzzles.

In addition, we have also released our code for generating such puzzles, see
https://github.com/deepmind/pushworld/blob/main/python3/scripts/generate_level0_puzzles.py

Best,
PushWorld team

**Comment by wcarvalho** [comment]
Thank you so much!
