### ISSUE TITLE
Can't import pushworld 

### ISSUE THREAD

**Issue by tkelestemur** [deepmind/pushworld#3]
Hello, thanks for the great library!

I've followed the installation instructions on the README but when I try to load environment I'm getting `ModuleNotFoundError`. How can I make sure the pushworld is installed into the venv environment? 

```
/Users/tkelestemur/projects/libs/pushworld/python3
(push-world) ➜  python3 git:(main) ✗ python scripts/demo_gym_env.py
Traceback (most recent call last):
  File "/Users/tkelestemur/projects/libs/pushworld/python3/scripts/demo_gym_env.py", line 20, in <module>
    from pushworld.puzzle import NUM_ACTIONS
ModuleNotFoundError: No module named 'pushworld'
```

**Comment by kkansky** [comment]
Hi Tarik! I tried a fresh install and wasn't able to reproduce this issue. In the `pushworld/python3` directory, have you run `source venv/bin/activate`? Or maybe you need to run `deactivate` first because you are in a different virtual environment?

Here are the commands that work for me:
```
git clone git@github.com:deepmind/pushworld.git
cd pushworld/python3
./setup.py
source venv/bin/activate
pytest test/test_puzzle.py
```

**Comment by tkelestemur** [comment]
This script creates a `pushworld.pth` file under the `<python libs dir>/site-packages` and writes `../../../../src` into the file which does not link to the correct folder. I manually changed it to the full path of the folder as `/Users/tkelestemur/projects/libs/pushworld/python3/src` which fixed the problem.

**Comment by peterdavidfagan** [comment]
I also faced the same error as @tkelestemur, I opened a pr that should address this. 

Note: this change only works when the setup.sh script is run from the directory containing it (and importantly containing the src folder). This solution is not robust.
